//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKON.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
    
    
    public partial class Article
    {
        public Article()
        {
            this.Liste_produit_achat = new HashSet<Liste_produit_achat>();
            this.Liste_produit = new HashSet<Liste_produit>();
            this.Liste_produit_vente = new HashSet<Liste_produit_vente>();
        }
    
        public short Id_article { get; set; }
        [DisplayName("Libellé")]
        [Required(ErrorMessage = "Le libellé est obligatoire")]
        public string Libelle_article { get; set; }
        //[Required(ErrorMessage = "La famille est obligatoire")]
        public Nullable<short> Id_famille { get; set; }
        public Nullable<int> Qte_article { get; set; }
        [DisplayName("Stock critique")]
        [Required(ErrorMessage = "Le stock critique est obligatoire")]
        public Nullable<int> Stock_critique { get; set; }
        [DisplayName("Prix grossite")]
        public Nullable<decimal> Prix_grossiste { get; set; }
        [DisplayName("Prix détaillant")]
        public Nullable<decimal> Prix_detaillant { get; set; }
        [Required(ErrorMessage = "Le conditionnement est obligatoire")]
        public string Conditionnement { get; set; }
        [DisplayName("Code")]
        [Required(ErrorMessage = "Le colde est obligatoire")]
        public string Code_article { get; set; }
    
        public virtual Famille_article Famille_article { get; set; }
        public virtual ICollection<Liste_produit_achat> Liste_produit_achat { get; set; }
        public virtual ICollection<Liste_produit> Liste_produit { get; set; }
        public virtual ICollection<Liste_produit_vente> Liste_produit_vente { get; set; }
    }
}
