//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKON.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Facture_vente
    {
        public Facture_vente()
        {
            this.Liste_produit_vente = new HashSet<Liste_produit_vente>();
            this.Reglement = new HashSet<Reglement>();
        }

        public short Id_facture { get; set; }
        [DisplayName("Client")]
        //[Required(ErrorMessage = "Le fournisseur est obligatoire")]
        public Nullable<short> Id_client { get; set; }
        [DisplayName("Date")]
        [Required(ErrorMessage = "La date est obligatoire")]
        public System.DateTime Date_facture { get; set; }
        [DisplayName("Mode de règlement")]
        //[Required(ErrorMessage = "Le mode de règlement est obligatoire")]
        public string Mode_reglement { get; set; }
        [DisplayName("Type")]
        //[Required(ErrorMessage = "Le type est obligatoire")]
        public string Type_facture { get; set; }
        [DisplayName("Code")]
        [Required(ErrorMessage = "Le colde est obligatoire")]
        public string Code_facture { get; set; }
        public double Remise { get; set; }
        public Boolean TVA { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Liste_produit_vente> Liste_produit_vente { get; set; }
        public virtual ICollection<Reglement> Reglement { get; set; }
    }
}
