//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKON.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Famille_article
    {
        public Famille_article()
        {
            this.Article = new HashSet<Article>();
        }
    
        public short Id_famille { get; set; }
        [DisplayName("Libellé")]
        [Required(ErrorMessage = "Le libellé est obligatoire")]
        public string Libelle_famille { get; set; }

        [DisplayName("Conditionnement")]
        [Required(ErrorMessage = "Le conditionnement est obligatoire")]
        public string Conditionnement { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
    }
}
