//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKON.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Fournisseur
    {
        public Fournisseur()
        {
            this.Facture_achat = new HashSet<Facture_achat>();
        }
        
        public short Id_fournisseur { get; set; }
        [DisplayName("Nom")]
        [Required(ErrorMessage = "Le nom est obligatoire")]
        public string Nom_fournisseur { get; set; }
        [DisplayName("prénom")]
        public string Prenom_fournisseur { get; set; }
        [DisplayName("Adresse")]
        public string Adresse_fournisseur { get; set; }
        [DisplayName("Téléphone")]
        public string Telephone_fournisseur { get; set; }
        [DisplayName("Email")]
        public string Mail__fournisseur { get; set; }
        [DisplayName("Code")]
        [Required(ErrorMessage = "Le colde est obligatoire")]
        public string Code_fournisseur { get; set; }
    
        public virtual ICollection<Facture_achat> Facture_achat { get; set; }
    }
}
