//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKON.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Script.Serialization;
    
    public partial class Liste_produit_achat
    {
        [DisplayName("Article")]
        public short Id_article { get; set; }
        [DisplayName("Facture")]
        public short Id_facture { get; set; }
        [Required(ErrorMessage = "La quantité est obligatoire")]
        [DisplayName("Quantité")]
        public Nullable<int> Quantite { get; set; }
        [Required(ErrorMessage = "Le prix est obligatoire")]
        [DisplayName("PU")]
        public Nullable<decimal> Prix { get; set; }
        [DisplayName("PT")]
        
        public Nullable<decimal> Prix_total { get; set; }
        [ScriptIgnore]
        [UIHint("ListeArticle")]
        public virtual Article Article { get; set; }
        [ScriptIgnore]
        public virtual Facture_achat Facture_achat { get; set; }
    }
}
