//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public short Id { get; set; }
        public string Utilisateur { get; set; }
        public string Operation { get; set; }
        public string Date { get; set; }
        public string TableOP { get; set; }
    }
}
