//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOCKON.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Mouvement_stock
    {
        public Mouvement_stock()
        {
            this.Liste_produit = new HashSet<Liste_produit>();
        }
    
        public short ID_mouvement { get; set; }
        [DisplayName("Date")]
        [Required(ErrorMessage = "La date est obligatoire")]
        public System.DateTime Date_mouvement { get; set; }
        [DisplayName("Type")]
       // [Required(ErrorMessage = "Le type est obligatoire")]
        public string Type_mouvement { get; set; }
        [DisplayName("Libellé")]
        [Required(ErrorMessage = "Le libellé est obligatoire")]
        public string Libelle_mouvement { get; set; }
       // public string Numero_mouvement { get; set; }
        [DisplayName("Code")]
        [Required(ErrorMessage = "Le colde est obligatoire")]
        public string Code_mouvement { get; set; }
    
        public virtual ICollection<Liste_produit> Liste_produit { get; set; }
    }
}
